// src/components/forms/FormSteps.tsx
import type { ReactNode } from "react";
import { Button } from "@/components/ui/button";

type Step = {
  value: string;
  label: string;
};

export default function FormSteps({
  items,
  value,
  onValueChange,
  label,
  children,
}: {
  items: readonly Step[];
  value: string;
  onValueChange: (value: string) => void;
  label: string;
  children: ReactNode;
}) {
  return (
    <div data-ui="form-steps">
      <nav aria-label={label} data-part="navigation">
        <ol data-part="list">
          {items.map((item, index) => {
            const active = item.value === value;

            return (
              <li key={item.value} data-state={active ? "active" : "inactive"}>
                <Button
                  type="button"
                  variant="ghost"
                  data-part="trigger"
                  aria-current={active ? "step" : undefined}
                  onClick={() => onValueChange(item.value)}
                >
                  <span data-part="number">{index + 1}</span>
                  <span data-part="label">{item.label}</span>
                </Button>
              </li>
            );
          })}
        </ol>
      </nav>
      <div data-part="content">{children}</div>
    </div>
  );
}

// src/lib/ui/patterns/FormSteps.svelte
<script lang="ts" module>
  export type FormStep = {
    label: string;
    value: string;
  };
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import Button from "../primitives/Button.svelte";

  let {
    children,
    items,
    label,
    onValueChange,
    value = $bindable(items[0]?.value ?? ""),
  }: {
    children: Snippet;
    items: readonly FormStep[];
    label: string;
    onValueChange?: (value: string) => void;
    value?: string;
  } = $props();

  const resolvedValue = $derived(
    items.some((item) => item.value === value) ? value : (items[0]?.value ?? "")
  );

  function select(nextValue: string) {
    value = nextValue;
    onValueChange?.(nextValue);
  }
</script>

<div data-ui="form-steps">
  <nav data-part="navigation" aria-label={label}>
    <ol data-part="list">
      {#each items as item, index (item.value)}
        <li data-state={item.value === resolvedValue ? "active" : "inactive"}>
          <Button
            data-part="trigger"
            variant="ghost"
            size="small"
            aria-current={item.value === resolvedValue ? "step" : undefined}
            onclick={() => select(item.value)}
          >
            <span data-part="number">{index + 1}</span>
            <span>{item.label}</span>
          </Button>
        </li>
      {/each}
    </ol>
  </nav>
  <div data-part="content">{@render children()}</div>
</div>
