// src/components/admin/SettingsSection.tsx
import type { ReactNode } from "react";
import { cn } from "@/lib/utils";

type Props = {
  title: string;
  description?: string;
  eyebrow?: string;
  icon?: ReactNode;
  children: ReactNode;
  embedded?: boolean;
  tone?: "default" | "danger";
  className?: string;
};

export default function SettingsSection({
  title,
  description,
  eyebrow,
  icon,
  children,
  embedded = false,
  tone = "default",
  className,
}: Props) {
  return (
    <section
      className={cn("settings-section", embedded && "settings-section--embedded", className)}
      data-tone={tone}
    >
      <header className="settings-section__header">
        {icon ? (
          <span className="settings-section__icon" aria-hidden="true">
            {icon}
          </span>
        ) : null}
        <span className="settings-section__heading">
          {eyebrow ? <span className="settings-section__eyebrow">{eyebrow}</span> : null}
          <h2>{title}</h2>
          {description ? <p>{description}</p> : null}
        </span>
      </header>
      <div className="settings-section__body">{children}</div>
    </section>
  );
}

// src/lib/ui/patterns/SettingsSection.svelte
<script lang="ts" module>
  export type SettingsSectionTone = "danger" | "default";
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = Omit<HTMLAttributes<HTMLElement>, "children" | "title"> & {
    children?: Snippet;
    description?: string;
    embedded?: boolean;
    eyebrow: string;
    title: string;
    tone?: SettingsSectionTone;
  };

  let {
    children,
    description,
    embedded = false,
    eyebrow,
    title,
    tone = "default",
    ...attributes
  }: Props = $props();

  const headingId = $props.id();
</script>

<section
  {...attributes}
  data-ui="settings-section"
  data-embedded={embedded || undefined}
  data-tone={tone}
  aria-labelledby={headingId}
>
  <header data-part="header">
    <div data-part="intro">
      <span data-part="eyebrow">{eyebrow}</span>
      <h2 id={headingId} data-part="title">{title}</h2>
      {#if description}<p data-part="description">{description}</p>{/if}
    </div>
  </header>
  <div data-part="content">{@render children?.()}</div>
</section>
