// src/components/ui/button.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Slot } from "radix-ui"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center rounded-lg border border-transparent bg-clip-padding text-[length:var(--app-type-body-sm)] font-semibold whitespace-nowrap transition-all outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/30 active:not-aria-[haspopup]:translate-y-px disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground shadow-sm [a]:hover:bg-primary/90",
        outline:
          "border-border bg-background hover:border-input hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:border-input dark:bg-input/30 dark:hover:bg-input/50",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80 aria-expanded:bg-secondary aria-expanded:text-secondary-foreground",
        ghost:
          "hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:hover:bg-muted/50",
        destructive:
          "bg-destructive/10 text-destructive hover:bg-destructive/20 focus-visible:border-destructive/40 focus-visible:ring-destructive/20 dark:bg-destructive/20 dark:hover:bg-destructive/30 dark:focus-visible:ring-destructive/40",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default:
          "h-10 gap-2 px-4 has-data-[icon=inline-end]:pr-3 has-data-[icon=inline-start]:pl-3",
        xs: "h-8 gap-1.5 rounded-[min(var(--radius-md),10px)] px-2.5 text-[length:var(--app-type-label)] in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-9 gap-1.5 rounded-[min(var(--radius-md),12px)] px-3 text-[length:var(--app-type-body-sm)] in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-2.5 has-data-[icon=inline-start]:pl-2.5 [&_svg:not([class*='size-'])]:size-3.5",
        lg: "h-11 gap-2 px-5 has-data-[icon=inline-end]:pr-4 has-data-[icon=inline-start]:pl-4",
        icon: "size-10",
        "icon-xs":
          "size-6 rounded-[min(var(--radius-md),10px)] in-data-[slot=button-group]:rounded-lg [&_svg:not([class*='size-'])]:size-3",
        "icon-sm":
          "size-9 rounded-[min(var(--radius-md),12px)] in-data-[slot=button-group]:rounded-lg",
        "icon-lg": "size-11",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot.Root : "button"

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }

// src/lib/ui/primitives/Button.svelte
<script lang="ts">
  import type { HTMLButtonAttributes } from "svelte/elements";
  import type { PublicHtmlAttributes } from "../public-html-attributes";

  export type ButtonVariant = "primary" | "secondary" | "destructive" | "ghost";
  export type ButtonSize = "small" | "default" | "icon" | "compact-icon";

  type Props = PublicHtmlAttributes<HTMLButtonAttributes> & {
    fullWidth?: boolean;
    variant?: ButtonVariant;
    size?: ButtonSize;
  };

  let {
    children,
    fullWidth = false,
    type = "button",
    variant = "primary",
    size = "default",
    ...attributes
  }: Props = $props();
</script>

<button
  {...attributes}
  class={[
    "inline-flex items-center justify-center gap-control-gap border font-action text-center no-underline whitespace-nowrap cursor-pointer transition duration-120 focus-visible:outline-3 focus-visible:outline-focus-outline focus-visible:outline-offset-2 enabled:active:translate-y-px disabled:cursor-not-allowed disabled:opacity-50",
    "min-w-0",
    fullWidth && "w-full",
    "rounded-control",
    variant === "primary"
      ? "border-transparent bg-brand text-action-primary-text enabled:hover:bg-action-primary-hover"
      : variant === "secondary"
        ? "border-line-strong bg-action-secondary text-ink enabled:hover:bg-surface-subtle"
        : variant === "destructive"
          ? "border-transparent bg-status-danger-bg text-status-danger-text enabled:hover:bg-action-destructive-hover"
          : variant === "ghost"
            ? "border-transparent bg-transparent enabled:hover:bg-surface-subtle"
            : "",
    variant === "ghost" && "text-ink",
    size === "default"
      ? "min-h-control px-action-inline py-control-block text-label leading-control"
      : size === "small"
        ? "min-h-compact-control px-control-inline py-action-compact-block text-caption leading-control"
        : size === "icon"
          ? "w-control min-h-control flex-none justify-center p-0 text-label leading-control"
          : "w-compact-control h-compact-control min-h-compact-control flex-none justify-center p-0",
  ]}
  {type}
  data-ui-primitive="button"
  data-variant={variant}
  data-size={size}
  data-full-width={fullWidth || undefined}
>
  {@render children?.()}
</button>
