// src/lib/features/arrangements/ArrangementRow.svelte
<script lang="ts">
  import type { ArrangementRespons } from "$lib/contracts";
  import { Button, CollectionRow, DocumentFacts, type DocumentFact } from "$lib/ui";
  import ArrangementCancelDialog from "./ArrangementCancelDialog.svelte";
  import {
    INITIAL_PROGRAM_DAY_COUNT,
    PROGRAM_DAYS_PER_PAGE,
    createArrangementListItem,
    formatCourts,
    formatProgramDate,
  } from "./model";

  let {
    arrangement,
    cancelError,
    cancelling = false,
    onCancel,
    onPrepareCancel,
    onResetCancel,
    referenceDate,
  }: {
    arrangement: ArrangementRespons;
    cancelError?: string | null;
    cancelling?: boolean;
    onCancel: () => Promise<unknown>;
    onPrepareCancel: () => void;
    onResetCancel: () => void;
    referenceDate?: Date;
  } = $props();

  let visibleDayCount = $state(INITIAL_PROGRAM_DAY_COUNT);
  const generatedId = $props.id();
  const programHeadingId = `${generatedId}-program`;
  const item = $derived(createArrangementListItem(arrangement, referenceDate));
  const visibleDays = $derived(item.programDays.slice(0, visibleDayCount));
  const programFacts = $derived(
    visibleDays.flatMap((day) =>
      day.slots.map(
        (slot): DocumentFact => ({
          label: `${formatProgramDate(day.dato)}, ${slot.startTid.slice(0, 5)}–${slot.sluttTid.slice(0, 5)}`,
          value: formatCourts(slot.baneNavn),
        })
      )
    )
  );
  const hasMoreDays = $derived(item.programDays.length > visibleDayCount);
</script>

{#snippet details()}
  {#if item.description}<p>{item.description}</p>{/if}

  {#if item.bookedBy}
    <DocumentFacts items={[{ label: "Booket av", value: item.bookedBy }]} />
  {/if}

  {#if item.programSummary}
    <section aria-labelledby={programHeadingId}>
      <h4 id={programHeadingId}>Program</h4>
      <p>{item.programSummary}</p>
      <DocumentFacts items={programFacts} label={`Program for ${arrangement.tittel}`} />
      {#if hasMoreDays}
        <Button
          variant="ghost"
          size="small"
          onclick={() => (visibleDayCount += PROGRAM_DAYS_PER_PAGE)}
        >
          Vis flere datoer
        </Button>
      {/if}
    </section>
  {:else if !arrangement.erPassert}
    <p>Ingen kommende tider i programmet.</p>
  {/if}
{/snippet}

{#snippet actions()}
  <ArrangementCancelDialog
    title={arrangement.tittel}
    error={cancelError}
    pending={cancelling}
    {onCancel}
    onPrepare={onPrepareCancel}
    onReset={onResetCancel}
  />
{/snippet}

<CollectionRow
  title={arrangement.tittel}
  description={item.metadata}
  meta={[item.dateRange.label, item.relativeStart].filter(Boolean).join(" · ")}
  status={item.lifecycle}
  muted={arrangement.erPassert}
  busy={cancelling}
  interaction={item.hasDetails
    ? {
        type: "expand",
        value: arrangement.id,
        details,
        actions: item.canCancel ? actions : undefined,
      }
    : { type: "static" }}
/>

// src/features/arrangementer/views/arrangementer/ArrangementRow.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  RecordDateRange,
  RecordEmptyNote,
  RecordFacts,
  RecordProgram,
  RecordProgramDay,
  RecordProgramDays,
  RecordProgramHeader,
  RecordProgramMore,
  RecordProgramSlot,
} from "@/components/records";
import { Collection } from "@/components";
import { SlettArrangementDialog } from "@/features/arrangement-admin/components";
import type { ArrangementRespons, DagMedSlotsRespons } from "@/types";
import { dagerIgjenTekst } from "@/utils/datoUtils";
import { harHandling } from "@/utils/handlingUtils";
import { Kapabiliteter } from "@/utils/kapabiliteter";
import {
  formaterArrangementMetadata,
  getArrangementLifecycleStatus,
} from "@/utils/arrangementPresentation";

type Props = {
  arrangement: ArrangementRespons;
  onAvlys: (arrangement: ArrangementRespons) => Promise<unknown>;
};

const INITIAL_DATOER = 3;
const DATOER_PER_KLIKK = 3;

function parseLocalDate(date: string) {
  return new Date(`${date.slice(0, 10)}T00:00:00`);
}

function todayIso() {
  const today = new Date();
  const year = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, "0");
  const day = String(today.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function formatRelativeStart(date: string) {
  return `Starter ${dagerIgjenTekst(date).toLocaleLowerCase("nb-NO")}`;
}

function formatShortDate(date: string, includeYear = false) {
  return parseLocalDate(date).toLocaleDateString("nb-NO", {
    day: "numeric",
    month: "short",
    ...(includeYear ? { year: "numeric" } : {}),
  });
}

function formatDateRange(arrangement: ArrangementRespons) {
  const startYear = parseLocalDate(arrangement.startDato).getFullYear();
  const endYear = parseLocalDate(arrangement.sluttDato).getFullYear();
  const currentYear = new Date().getFullYear();
  const includeStartYear = startYear !== currentYear || startYear !== endYear;
  const includeEndYear = endYear !== currentYear;

  if (arrangement.startDato === arrangement.sluttDato) {
    return { start: formatShortDate(arrangement.startDato, includeStartYear), end: null };
  }

  return {
    start: formatShortDate(arrangement.startDato, includeStartYear),
    end: formatShortDate(arrangement.sluttDato, includeEndYear),
  };
}

function formatProgramDate(date: string) {
  const formatted = parseLocalDate(date).toLocaleDateString("nb-NO", {
    weekday: "long",
    day: "numeric",
    month: "long",
  });
  return formatted.charAt(0).toLocaleUpperCase("nb-NO") + formatted.slice(1);
}

function getUpcomingDays(days: DagMedSlotsRespons[]) {
  const today = todayIso();
  return days.filter((day) => day.dato >= today && day.slots.length > 0);
}

function createProgramSummary(days: DagMedSlotsRespons[]) {
  const upcomingDays = getUpcomingDays(days);
  const slots = upcomingDays.flatMap((day) => day.slots);

  if (slots.length === 0) return null;

  const start = slots.map((slot) => slot.startTid.slice(0, 5)).sort()[0];
  const end = slots
    .map((slot) => slot.sluttTid.slice(0, 5))
    .sort()
    .at(-1);

  return {
    count: slots.length,
    dayCount: upcomingDays.length,
    timeRange: `${start}–${end}`,
  };
}

function formatCourts(courts: string[]) {
  const sorted = [...courts].sort();
  if (sorted.length <= 2) return sorted.join(" og ");
  return `${sorted.slice(0, -1).join(", ")} og ${sorted.at(-1)}`;
}

export default function ArrangementRow({ arrangement, onAvlys }: Props) {
  const [visibleDayCount, setVisibleDayCount] = useState(INITIAL_DATOER);

  const description = arrangement.beskrivelse?.trim() ?? "";
  const upcomingDays = getUpcomingDays(arrangement.slotsPrDag ?? []);
  const programSummary = createProgramSummary(arrangement.slotsPrDag ?? []);
  const nextDate = upcomingDays[0]?.dato ?? null;
  const visibleDays = upcomingDays.slice(0, visibleDayCount);
  const hasMoreDays = upcomingDays.length > visibleDayCount;
  const dates = formatDateRange(arrangement);
  const lifecycleStatus = getArrangementLifecycleStatus(arrangement);
  const relativeStart =
    lifecycleStatus.label === "Kommende" && nextDate ? formatRelativeStart(nextDate) : undefined;
  const metadata = formaterArrangementMetadata(arrangement);

  const canCancel =
    !arrangement.erPassert &&
    harHandling(arrangement.kapabiliteter, Kapabiliteter.arrangement.avlys);
  const hasActions = canCancel;
  const hasDetails =
    !!description ||
    !!arrangement.booketAv ||
    !!programSummary ||
    hasActions ||
    (!arrangement.erPassert && !programSummary);

  return (
    <Collection.Row
      leading={<RecordDateRange start={dates.start} end={dates.end} />}
      title={arrangement.tittel}
      description={metadata}
      meta={relativeStart}
      status={lifecycleStatus}
      muted={arrangement.erPassert}
      interaction={
        hasDetails
          ? {
              type: "expand",
              value: arrangement.id,
              details: (
                <>
                  {description ? <p>{description}</p> : null}

                  {arrangement.booketAv ? (
                    <RecordFacts items={[{ label: "Booket av", value: arrangement.booketAv }]} />
                  ) : null}

                  {programSummary ? (
                    <RecordProgram>
                      <RecordProgramHeader
                        title="Program"
                        summary={
                          <>
                            {programSummary.count} {programSummary.count === 1 ? "tid" : "tider"} ·{" "}
                            {programSummary.dayCount}{" "}
                            {programSummary.dayCount === 1 ? "dag" : "dager"} ·{" "}
                            {programSummary.timeRange}
                          </>
                        }
                      />

                      <RecordProgramDays>
                        {visibleDays.map(({ dato, slots }) => (
                          <RecordProgramDay
                            key={dato}
                            title={<time dateTime={dato}>{formatProgramDate(dato)}</time>}
                          >
                            {slots.map((slot) => (
                              <RecordProgramSlot
                                key={`${dato}-${slot.startTid}-${slot.sluttTid}-${slot.baneNavn.join("-")}`}
                                time={`${slot.startTid.slice(0, 5)}–${slot.sluttTid.slice(0, 5)}`}
                              >
                                {formatCourts(slot.baneNavn)}
                              </RecordProgramSlot>
                            ))}
                          </RecordProgramDay>
                        ))}

                        {hasMoreDays ? (
                          <RecordProgramMore
                            onClick={() => setVisibleDayCount((count) => count + DATOER_PER_KLIKK)}
                          >
                            Vis flere datoer
                          </RecordProgramMore>
                        ) : null}
                      </RecordProgramDays>
                    </RecordProgram>
                  ) : !arrangement.erPassert ? (
                    <RecordEmptyNote>Ingen kommende tider i programmet.</RecordEmptyNote>
                  ) : null}
                </>
              ),
              actions: hasActions ? (
                <>
                  {canCancel ? (
                    <SlettArrangementDialog
                      tittel={arrangement.tittel}
                      onSlett={() => onAvlys(arrangement).then(() => undefined)}
                      trigger={
                        <Button type="button" variant="destructive" size="sm">
                          Avlys
                        </Button>
                      }
                    />
                  ) : null}
                </>
              ) : undefined,
            }
          : { type: "static" }
      }
    />
  );
}
