// src/lib/ui/patterns/Section.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  export type SectionVariant = "soft" | "surface" | "plain";
  export type SectionPadding = "small" | "medium" | "large";

  type Props = Omit<HTMLAttributes<HTMLElement>, "children" | "title"> & {
    actions?: Snippet;
    children?: Snippet;
    description?: string;
    padding?: SectionPadding;
    title?: string;
    variant?: SectionVariant;
  };

  let {
    actions,
    children,
    description,
    padding = "medium",
    title,
    variant = "soft",
    ...attributes
  }: Props = $props();

  const headingId = $props.id();
  const hasHeader = $derived(Boolean(title || description || actions));
  const dataPadding = $derived(padding === "small" ? "sm" : padding === "large" ? "lg" : "md");
</script>

<section
  {...attributes}
  data-ui="section"
  data-variant={variant}
  data-padding={dataPadding}
  aria-labelledby={title ? headingId : undefined}
>
  {#if hasHeader}
    <header data-ui="section-header">
      <div data-part="intro">
        {#if title}<h2 id={headingId} data-part="title">{title}</h2>{/if}
        {#if description}<p data-part="description">{description}</p>{/if}
      </div>
      {#if actions}<div data-part="actions">{@render actions()}</div>{/if}
    </header>
  {/if}
  <div data-part="content">{@render children?.()}</div>
</section>

// src/components/section/index.tsx
import type { ComponentProps, ReactNode } from "react";

type SectionProps = Omit<ComponentProps<"section">, "title" | "children"> & {
  title?: ReactNode;
  description?: ReactNode;
  actions?: ReactNode;
  children: ReactNode;
  variant?: "soft" | "surface" | "plain";
  padding?: "sm" | "md" | "lg";
};

function SectionRoot({
  title,
  description,
  actions,
  children,
  className,
  variant = "soft",
  padding = "md",
  ...props
}: SectionProps) {
  const showHeader = Boolean(title || description || actions);

  return (
    <section
      {...props}
      className={className}
      data-ui="section"
      data-variant={variant}
      data-padding={padding}
    >
      {showHeader ? (
        <Heading actions={actions} description={description}>
          {title}
        </Heading>
      ) : null}
      <div data-part="content">{children}</div>
    </section>
  );
}

function Heading({
  children,
  description,
  actions,
  className,
}: {
  children?: ReactNode;
  description?: ReactNode;
  actions?: ReactNode;
  className?: string;
}) {
  return (
    <header className={className} data-ui="section-header">
      <div data-part="intro">
        {children ? <h2 data-part="title">{children}</h2> : null}
        {description ? <p data-part="description">{description}</p> : null}
      </div>
      {actions ? <div data-part="actions">{actions}</div> : null}
    </header>
  );
}

const Section = Object.assign(SectionRoot, { Heading });

export default Section;
