// src/features/booking/components/BookingSlotRow.tsx
import { memo } from "react";
import { Collection } from "@/components";
import WeatherInfo from "@/components/WeatherInfo";
import { Stack, Text } from "@/components/layout";
import { RecordFacts, RecordTimeRange, type RecordStatusTone } from "@/components/records";
import { Button } from "@/components/ui/button";
import type { BookingSlotRespons, SlotStatus } from "@/types";
import KobleTilArrangementDialog from "./KobleTilArrangementDialog";
import { getBookingSlotPresentation } from "./bookingSlotPresentation";

type Props = {
  grenId: string;
  slot: BookingSlotRespons;
  isAuthenticated: boolean;
  onBook?: (slot: BookingSlotRespons, arrangementId?: string) => void;
  onFjern?: (slot: BookingSlotRespons) => void;
};

function getStatusTone(status: SlotStatus): RecordStatusTone {
  if (status === "ledig") return "available";
  if (status === "passert") return "past";
  return "busy";
}

function BookingSlotRow({ grenId, slot, isAuthenticated, onBook, onFjern }: Props) {
  const presentation = getBookingSlotPresentation(slot, isAuthenticated);
  const isArrangement = presentation.status === "arrangement";
  const arrangementBooker = slot.arrangementTittel ? slot.booketAv?.trim() : null;
  const hasWeather = slot.værSymbol || typeof slot.temperatur === "number";
  const quickAction = presentation.kanHurtigbooke ? (
    <Button
      size="sm"
      onClick={() => onBook?.(slot)}
      aria-label={`Book tiden ${presentation.startTid} til ${presentation.sluttTid}`}
    >
      Book
    </Button>
  ) : undefined;

  const hasDetailContent = Boolean(
    slot.arrangementBeskrivelse || arrangementBooker || presentation.kanIkkeBooke
  );
  const details = hasDetailContent ? (
    <Stack gap="lg">
      {slot.arrangementBeskrivelse ? (
        <Text variant="muted">{slot.arrangementBeskrivelse}</Text>
      ) : null}

      {arrangementBooker ? (
        <RecordFacts items={[{ label: "Booket av", value: arrangementBooker }]} />
      ) : null}

      {presentation.kanIkkeBooke ? (
        <Text variant="muted">
          Du kan ikke booke denne tiden akkurat nå. Maks antall bookinger kan være nådd.
        </Text>
      ) : null}
    </Stack>
  ) : undefined;

  const actions =
    presentation.kanKobleTilArrangement || presentation.kanFjerne ? (
      <>
        {presentation.kanKobleTilArrangement ? (
          <KobleTilArrangementDialog
            grenId={grenId}
            valgtId={null}
            onVelg={(arrangementId) => {
              if (arrangementId) onBook?.(slot, arrangementId);
            }}
          >
            <Button variant="outline" size="sm">
              Koble til arrangement
            </Button>
          </KobleTilArrangementDialog>
        ) : null}

        {presentation.kanFjerne ? (
          <Button variant="destructive" size="sm" onClick={() => onFjern?.(slot)}>
            Avbestill
          </Button>
        ) : null}
      </>
    ) : undefined;
  const interaction = presentation.harDetaljer
    ? ({
        type: "expand",
        value: presentation.slotKey,
        details,
        actions,
        summaryAction: quickAction,
      } as const)
    : quickAction
      ? ({ type: "action", action: quickAction } as const)
      : ({ type: "static" } as const);

  return (
    <Collection.Row
      layout="schedule"
      muted={slot.erPassert}
      leading={
        <RecordTimeRange
          start={presentation.startTid}
          end={presentation.sluttTid}
          accessory={
            hasWeather ? (
              <WeatherInfo
                værSymbol={slot.værSymbol}
                temperatur={slot.temperatur}
                vind={slot.vind}
                compact
              />
            ) : undefined
          }
        />
      }
      title={presentation.tittel}
      category={isArrangement ? { label: "Arrangement", tone: "event" } : undefined}
      status={{ label: presentation.statusTekst, tone: getStatusTone(presentation.status) }}
      interaction={interaction}
    />
  );
}

export default memo(BookingSlotRow);

// src/lib/features/booking/BookingSlotRow.svelte
<script lang="ts">
  import type { KalenderSlotRespons } from "$lib/contracts";
  import { Button, CollectionRow, DocumentFacts, ScheduleTime, Weather } from "$lib/ui";
  import ArrangementBookingDialog from "./ArrangementBookingDialog.svelte";
  import { getBookingSlotPresentation } from "./model";

  let {
    activityId,
    authenticated,
    busy = false,
    onBook,
    onCancel,
    slot,
  }: {
    activityId: string;
    authenticated: boolean;
    busy?: boolean;
    onBook: (slot: KalenderSlotRespons, arrangementId?: string) => void;
    onCancel: (slot: KalenderSlotRespons) => void;
    slot: KalenderSlotRespons;
  } = $props();

  const presentation = $derived(getBookingSlotPresentation(slot, authenticated));
  const arrangementOwner = $derived(slot.arrangementTittel ? slot.booketAv?.trim() : null);
</script>

{#snippet weather()}
  <Weather compact symbol={slot.værSymbol} temperature={slot.temperatur} wind={slot.vind} />
{/snippet}

{#snippet time()}
  <ScheduleTime
    start={presentation.start}
    end={presentation.end}
    accessory={slot.værSymbol || typeof slot.temperatur === "number" ? weather : undefined}
  />
{/snippet}

{#snippet quickBook()}
  <Button
    size="small"
    disabled={busy}
    aria-label={`Book tiden ${presentation.start} til ${presentation.end}`}
    onclick={() => onBook(slot)}
  >
    Book
  </Button>
{/snippet}

{#snippet details()}
  {#if slot.arrangementBeskrivelse}<p>{slot.arrangementBeskrivelse}</p>{/if}
  {#if arrangementOwner}
    <DocumentFacts items={[{ label: "Booket av", value: arrangementOwner }]} />
  {/if}
  {#if presentation.cannotBook}
    <p>Du kan ikke booke denne tiden akkurat nå. Maks antall bookinger kan være nådd.</p>
  {/if}
{/snippet}

{#snippet actions()}
  {#if presentation.canConnectToArrangement}
    <ArrangementBookingDialog
      {activityId}
      disabled={busy}
      onSelect={(arrangementId) => onBook(slot, arrangementId)}
    />
  {/if}
  {#if presentation.canCancel}
    <Button variant="destructive" size="small" disabled={busy} onclick={() => onCancel(slot)}>
      Avbestill
    </Button>
  {/if}
{/snippet}

{#if presentation.hasDetails}
  <CollectionRow
    layout="schedule"
    leading={time}
    title={presentation.title}
    category={presentation.category}
    status={presentation.status}
    muted={presentation.muted}
    {busy}
    interaction={{
      type: "expand",
      value: presentation.key,
      details,
      actions,
      summaryAction: presentation.canBook ? quickBook : undefined,
    }}
  />
{:else if presentation.canBook}
  <CollectionRow
    layout="schedule"
    leading={time}
    title={presentation.title}
    category={presentation.category}
    status={presentation.status}
    muted={presentation.muted}
    {busy}
    interaction={{ type: "action", action: quickBook }}
  />
{:else}
  <CollectionRow
    layout="schedule"
    leading={time}
    title={presentation.title}
    category={presentation.category}
    status={presentation.status}
    muted={presentation.muted}
    {busy}
  />
{/if}
