// src/lib/ui/patterns/EditorDialog.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import Button from "../primitives/Button.svelte";
  import DialogDescription from "../primitives/DialogDescription.svelte";
  import DialogPrimitive from "../primitives/DialogPrimitive.svelte";
  import DialogTitle from "../primitives/DialogTitle.svelte";

  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children" | "title"> & {
    backLabel: string;
    children: Snippet;
    description: string;
    eyebrow: string;
    onClose?: () => void;
    open?: boolean;
    pending?: boolean;
    title: string;
  };

  let {
    backLabel,
    children: content,
    description,
    eyebrow,
    onClose,
    open = $bindable(false),
    pending = false,
    title,
    ...attributes
  }: Props = $props();
</script>

<DialogPrimitive bind:open {onClose} {pending} size="editor">
  {#snippet children({ close })}
    <div {...attributes} data-ui="editor-dialog" data-state={pending ? "pending" : "ready"}>
      <div data-part="header" data-surface="control">
        <Button data-part="back" disabled={pending} onclick={close} size="small" variant="ghost">
          <span data-part="back-icon" aria-hidden="true">←</span>
          {backLabel}
        </Button>

        <div data-part="intro">
          <span data-part="eyebrow">{eyebrow}</span>
          <DialogTitle data-part="title">{title}</DialogTitle>
          <DialogDescription data-part="description">{description}</DialogDescription>
        </div>
      </div>

      <div data-part="content">{@render content()}</div>
    </div>
  {/snippet}
</DialogPrimitive>

// src/components/dialogs/EditorDialog.tsx
import type { ReactNode } from "react";
import { ArrowLeft } from "lucide-react";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  backLabel: string;
  eyebrow: string;
  title: string;
  description: string;
  children: ReactNode;
  trigger?: ReactNode;
  closeDisabled?: boolean;
};

export default function EditorDialog({
  open,
  onOpenChange,
  backLabel,
  eyebrow,
  title,
  description,
  children,
  trigger,
  closeDisabled = false,
}: Props) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      {trigger ? <DialogTrigger asChild>{trigger}</DialogTrigger> : null}
      <DialogContent data-ui="editor-dialog" showCloseButton={false}>
        <DialogHeader data-part="header" data-surface="control">
          <DialogClose asChild>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              data-part="back"
              disabled={closeDisabled}
            >
              <ArrowLeft data-icon="inline-start" aria-hidden="true" />
              {backLabel}
            </Button>
          </DialogClose>

          <div data-part="intro">
            <span data-part="eyebrow">{eyebrow}</span>
            <DialogTitle>{title}</DialogTitle>
            <DialogDescription>{description}</DialogDescription>
          </div>
        </DialogHeader>

        <div data-part="content">{children}</div>
      </DialogContent>
    </Dialog>
  );
}
