// src/lib/ui/patterns/SettingsSection.svelte
<script lang="ts" module>
  export type SettingsSectionTone = "danger" | "default";
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = Omit<HTMLAttributes<HTMLElement>, "children" | "title"> & {
    children?: Snippet;
    description?: string;
    embedded?: boolean;
    eyebrow: string;
    title: string;
    tone?: SettingsSectionTone;
  };

  let {
    children,
    description,
    embedded = false,
    eyebrow,
    title,
    tone = "default",
    ...attributes
  }: Props = $props();

  const headingId = $props.id();
</script>

<section
  {...attributes}
  data-ui="settings-section"
  data-embedded={embedded || undefined}
  data-tone={tone}
  aria-labelledby={headingId}
>
  <header data-part="header">
    <div data-part="intro">
      <span data-part="eyebrow">{eyebrow}</span>
      <h2 id={headingId} data-part="title">{title}</h2>
      {#if description}<p data-part="description">{description}</p>{/if}
    </div>
  </header>
  <div data-part="content">{@render children?.()}</div>
</section>

// src/components/settings/SettingsSection.tsx
import type { ReactNode } from "react";

export type SettingsSectionProps = {
  eyebrow: string;
  title: string;
  description?: string;
  children: ReactNode;
  embedded?: boolean;
  tone?: "default" | "danger";
  className?: string;
};

export default function SettingsSection({
  title,
  description,
  eyebrow,
  children,
  embedded = false,
  tone = "default",
  className,
}: SettingsSectionProps) {
  return (
    <section
      className={className}
      data-ui="settings-section"
      data-embedded={embedded || undefined}
      data-tone={tone}
    >
      <header data-part="header">
        <span data-part="intro">
          <span data-part="eyebrow">{eyebrow}</span>
          <h2 data-part="title">{title}</h2>
          {description ? <p data-part="description">{description}</p> : null}
        </span>
      </header>
      <div data-part="content">{children}</div>
    </section>
  );
}
