// src/lib/ui/patterns/FormActions.svelte
<script lang="ts" module>
  export type FormActionsAlign = "between" | "end" | "start";
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    align?: FormActionsAlign;
    children?: Snippet;
    embedded?: boolean;
    fullWidth?: boolean;
  };

  let {
    align = "end",
    children,
    embedded = true,
    fullWidth = false,
    ...attributes
  }: Props = $props();
</script>

<div
  {...attributes}
  data-ui="form-actions"
  data-align={align}
  data-embedded={embedded ? "true" : undefined}
  data-full-width={fullWidth ? "true" : undefined}
>
  {@render children?.()}
</div>

// src/components/forms/FormActions.tsx
import type { ReactNode } from "react";

type Props = {
  children: ReactNode;
  className?: string;

  /** Standard: høyrejustert */
  align?: "left" | "right" | "between";

  /** Luft over actions */
  spaced?: boolean;

  /** Ny: sticky actions nederst på skjermen */
  variant?: "inline" | "sticky";
  embedded?: boolean;
  fullWidth?: boolean;
};

export default function FormActions({
  children,
  className,
  align = "right",
  spaced = false,
  variant = "inline",
  embedded = true,
  fullWidth = false,
}: Props) {
  return (
    <div
      className={className}
      data-ui="form-actions"
      data-align={align}
      data-spaced={spaced || undefined}
      data-variant={variant}
      data-embedded={embedded || undefined}
      data-full-width={fullWidth || undefined}
    >
      {children}
    </div>
  );
}
