// src/lib/ui/patterns/FormField.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import {
    setFormControlContext,
    type FormControlContext,
  } from "../primitives/form-control-context";
  import { isInsideFormFields } from "./form-fields-context";

  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children: Snippet;
    controlId?: string;
    description?: string;
    error?: string | null;
    label: string;
    required?: boolean;
  };

  let {
    children,
    controlId,
    description,
    error,
    label,
    required = false,
    ...attributes
  }: Props = $props();

  if (!isInsideFormFields()) {
    throw new Error("FormField must be rendered inside FormFields.");
  }

  const generatedId = $props.id();
  const resolvedControlId = $derived(controlId ?? `${generatedId}-control`);
  const descriptionId = $derived(description ? `${resolvedControlId}-description` : undefined);
  const errorId = $derived(error ? `${resolvedControlId}-error` : undefined);

  const formControlContext: FormControlContext = {
    get controlId() {
      return resolvedControlId;
    },
    get descriptionId() {
      return descriptionId;
    },
    get errorId() {
      return errorId;
    },
    get invalid() {
      return Boolean(error);
    },
    get required() {
      return required;
    },
  };

  setFormControlContext(formControlContext);
</script>

<div {...attributes} data-ui="form-field" data-invalid={error ? "true" : undefined}>
  <div data-part="intro">
    <label for={resolvedControlId} data-part="label">
      {label}
      {#if required}<span data-part="required" aria-hidden="true">*</span>{/if}
    </label>
    {#if description}<p id={descriptionId} data-part="description">{description}</p>{/if}
  </div>
  <div data-part="control">
    {@render children()}
    {#if error}<p id={errorId} data-part="error" role="alert">{error}</p>{/if}
  </div>
</div>

// src/components/forms/FormField.tsx
import { createContext, useContext, type ReactNode } from "react";
import { Field, FieldDescription, FieldError, FieldLabel } from "@/components/ui/field";

const FormFieldsContext = createContext(false);

export function FormFields({ children }: { children: ReactNode }) {
  return (
    <FormFieldsContext.Provider value>
      <div data-ui="form-fields">{children}</div>
    </FormFieldsContext.Provider>
  );
}

export default function FormField({
  label,
  description,
  htmlFor,
  error,
  children,
}: {
  label: ReactNode;
  description?: ReactNode;
  htmlFor?: string;
  error?: ReactNode;
  children: ReactNode;
}) {
  const isInsideFormFields = useContext(FormFieldsContext);

  if (!isInsideFormFields) {
    throw new Error("Form.Field må brukes inni Form.Fields for å beholde felles skjemalayout.");
  }

  return (
    <Field data-ui="form-field" data-invalid={Boolean(error) || undefined}>
      <div data-part="intro">
        <FieldLabel htmlFor={htmlFor} data-part="label">
          {label}
        </FieldLabel>
        {description ? (
          <FieldDescription data-part="description">{description}</FieldDescription>
        ) : null}
      </div>
      <div data-part="control">
        {children}
        {error ? <FieldError>{error}</FieldError> : null}
      </div>
    </Field>
  );
}
